### ISSUE TITLE
Add Remove Word

### ISSUE THREAD

**Issue by jaime-franco** [web-mech/badwords#10]
It will be nice if there exist a method for remove a word.

**Comment by web-mech** [comment]
Explain the use-case? Also think about the strategy of maintaining a persistent list that can be modified by your application and re-instantiate the word filter with that list when necessary.

**Comment by jaime-franco** [comment]
We work with a list defined in the database and manage by a CMS, for example if a user add a word and want to removed from the CMS, it will be helpful to have a method for remove on fly, without to restart the server and add the words that are in database.

I write some code using the list parameter that the class has for remove the words, but it will be cool if the module has it built in that function.

Also there should be a way to enable and disable the population of the list from the json in the project,

**Comment by mindfulmike** [comment]
So i know its been a year since you requested this but here goes: 

Empty lists
https://github.com/web-mech/badwords#instantiate-with-an-empty-list

Removing words
https://github.com/web-mech/badwords#remove-words-from-the-blacklist
