### ISSUE TITLE
dose not filter custom words or wrods combined together

### ISSUE THREAD

**Issue by advocaite** [web-mech/badwords#11]
basicly 
it filters asshole to ******
if i type assholefuck, it wont filter 
if i add words like domain.com
if i type domain.com it dose not get filtered

**Comment by advocaite** [comment]
ok from what I can gather is the regex is what is stoping it
i can add domain to badwords its filtered but soon as i add the . then it breaks

**Comment by advocaite** [comment]
ok found something that works well and allows . in bad words

I set my own regex to this
filter = new Filter({regex: '\[^a-zA-z0-9:alnum:|\$|\@]|\^/gi'});
also on documentation you dont have regex inside '' so it will cause errors for the noobs out there

**Comment by web-mech** [comment]
You should be able to pass in raw regex in as the parameter. What you are currently passing in is a string and wont filter properly. Try using this syntax instead:

```
filter = new Filter({
    regex: /[^a-zA-z0-9:alnum:|\$|\@]|^/gi
  });
```

Notice the "/" in front of the regex, that will pass in an actual regular expression to the String.prototype.replace function and produce the expected outcome "domaincom" as the word for comparison against your blacklist.
