### ISSUE TITLE
"Gay" isn't a bad word?

### ISSUE THREAD

**Issue by joker314** [web-mech/badwords#12]
In my opinion, "gay" is not a bad word, just wondering why it was added. EDIT: As much as "straight" or "happy" are (both are synonyms to "gay")

If a homophobe uses it incorrectly it can be, but still

Your choice though

**Comment by CosmicWebServices** [comment]
That could be offensive as a bad word gay also means happy

**Comment by mindfulmike** [comment]
the words here are ported from the "What do you love" project from Google
https://gist.github.com/jamiew/1112488#file-google_twunter_lol
I simply baked it in as part of this project.

**Comment by facundomedica** [comment]
@web-mech @mindfulmike "gay" isn't in that list anymore. Shouldn't be listed imo

**Comment by trivoallan** [comment]
I think this issue should not have been closed. It's offensive and homophobic to see "gay" listed as a bad word.

**Comment by web-mech** [comment]
It has been removed with the latest release

**Comment by trivoallan** [comment]
Great, thanks :)
