### ISSUE TITLE
access to return value of profane

### ISSUE THREAD

**Issue by PaulieScanlon** [web-mech/badwords#13]
Hey, great library. I'm wondering if there's a way to check if profane is true or false. I'd like to trigger a message if a profanity is found as well as using the **** methods.

Thanks in advance.

**Comment by mindfulmike** [comment]
Hi Paulie,
The `isProfane` method would be the perfect use case for this.
# example

```
var Filter = require('bad-words'),
  filter = new Filter();

filter.isProfane('hello world'); // returns false
```

**Comment by PaulieScanlon** [comment]
Perfect! that's exactly what i was after, it works a treat! Thanks so much man!

**Comment by mindfulmike** [comment]
Glad to help!
