### ISSUE TITLE
Issue while replacing * when a string contains a matching word

### ISSUE THREAD

**Issue by awesomesolution** [web-mech/badwords#21]
Hello all,

I have used below code to replace my words list using this package. This doesn't work anymore when string contains word surrounds with extra characters.
`var Filter = require('bad-words');
var filter = new Filter({regex: /w/gi, list:['bad','word','some']}); 

filter.clean(" sobad wordme! sometimes");`

Thanks

**Comment by web-mech** [comment]
Resolved with https://github.com/web-mech/badwords/releases/tag/v1.6.0

**Comment by martinseanhunt** [comment]
Downgrading from current version to 1.6.0 fixed this for me
