### ISSUE TITLE
I have a question

### ISSUE THREAD

**Issue by gaxfor** [web-mech/badwords#23]
Filter.prototype.clean = function clean(string) {
    return string.split(/\b/).map(function(word) {
      return this.isProfane(word) ? this.replaceWord(word) : word;
    }.bind(this)).join('');
  };

In the above statement, why is \ b applied to the split function? In multilingual applications, except for English, \ b is not applied properly, so all sentences including exclusions are replaced by Placeholder Character.

**Comment by web-mech** [comment]
I'd need an example so i can better understand how i should parse the words. \b simple regex for word boundaries. Or I can make that part a configuration option and you decide how the words should be parsed.
