### ISSUE TITLE
[EVO] Add french-badwords-list as a french dictionary for french badwords

### ISSUE THREAD

**Issue by darwiin** [web-mech/badwords#27]
Hi,

I have made a little module with a consumable fench badwords list, would you be interested in integrating it as a dependency to your module ?

I would be pleased to work on a PR to add this as a native feature to your module.

Regards.

**Comment by egr-ext** [comment]
Hi, I would be interested by your french dictionary, can you share it ?
Thks

**Comment by darwiin** [comment]
You can add the [french-badwords-list](https://www.npmjs.com/package/french-badwords-list) as a dependency of badwords  and use the array to add words to your filter.

```javascript
var frenchBadwordsList = require('french-badwords-list');
 
// Only keep french badwords
frenchBadwordsList.array;
```

**Comment by egr-ext** [comment]
Merci Christophe. I will!

**Comment by web-mech** [comment]
I like the approach of keeping the dependencies light and adding on as needed. This is great by the way!
