### ISSUE TITLE
words that are not in blacklist are also filtered due to prefix/postfix matching.

### ISSUE THREAD

**Issue by MussaCharles** [web-mech/badwords#29]
Is there a way to avoid words such as title, button, etc and all other words that are not blacklisted but their prefix contains some of the bad words such as "tit" in "title" and "butt" in button? Thanks in advance.

**Comment by FZSS** [comment]
not sure about the cause but the following words are also true for isProfane:
entity
subclass
document

**Comment by nemaniarjun** [comment]
Its not just postfix / prefix matching. 
`entity` contains `tit`
`subclass` contains `ass`
`document` contains `cum`

**Comment by nicolasgarnier** [comment]
Even `Hello` is filtered :)

**Comment by jordanpurinton** [comment]
> Even Hello is filtered :)

Came here to mention this haha.

**Comment by web-mech** [comment]
Patched with https://github.com/web-mech/badwords/releases/tag/v1.6.2
