### ISSUE TITLE
isProfane not working

### ISSUE THREAD

**Issue by vallettea** [web-mech/badwords#33]
Hello,

just installed and did:
```
> filter.isProfane("go fuck")
'fuck'
> filter.isProfane("hello little boy")
'hello'
> filter.isProfane("hello go fuck")
'hello'
```

as I understand hello is not profane ?

wouldn't is be better if isProfane returns a boolean if one bad word is found in the string ?

**Comment by sheldon-sminq** [comment]
Yes hello seems to be tagged as a bad word

**Comment by web-mech** [comment]
Patched with https://github.com/web-mech/badwords/releases/tag/v1.6.2

**Comment by hpamnani** [comment]
Hi All,

I am trying to figure out how to get boolean value based on the string. I had a look at the documentation. However, I am not able to find it.

For example, I want "What the fuck" should return "true" and "What the heck" should return false.

It would be of great help if someone can help with the above issue.
