### ISSUE TITLE
Why can't I remove 'god'???

### ISSUE THREAD

**Issue by Hughp135** [web-mech/badwords#50]
FAILS
```
it('Should allow you to remove words from the filter blacklist and no longer filter them', () => {
      filter.removeWords('god');
      assert(filter.clean('This is a god test') === 'This is a god test');
});
```

Tried with capitals, etc, still doesn't work. I don't even know where 'god' gets added to the list anyway.

**Comment by web-mech** [comment]
@Hughp135 Thanks for the heads up! This should be fixed now with the latest release.
