### ISSUE TITLE
Not able to filter correctly.

### ISSUE THREAD

**Issue by knrt10** [web-mech/badwords#53]
I have an array and I am adding the bad words as a list but the function `clean` is not able to clean it correctly.

my code is 

```js
const filter = new Filter();
const newWords = ['cho', 'meo', 'chó', 'mèo'];
filter.addWords(...newWords);
console.log('this is message,', filter.clean(message.msg));
```

Output is `this is message, ***, ***, chó, mèo`. Please verify and help

**Comment by web-mech** [comment]
You'll need to leverage regex overrides in order to filter this correctly. Notice how the words without ó or è filter. Adjust your regex when constructing your filter and it should work.
https://github.com/web-mech/badwords#regex-overrides
