### ISSUE TITLE
Over-eager Soundex

### ISSUE THREAD

**Issue by mmerkes** [web-mech/badwords#7]
We're using this library as a safety net before emailing out user-generated content, and the soundex is catching a lot of benign words. Here's a test I wrote that fails:

```
it('should not over-eagerly mark words as profane', function () {
	assert(filter.isProfane("Should only take a minute but I don't own a mower") === false);
	assert(filter.isProfane('I have soldered a Radio Shack replacement jack onto the wire') === false);
});
```

The problematic words are 'should' and 'wire'. I forked the project and removed the soundex, which suits our needs, but I'm filing an issue in case everyone is having the issue.

**Comment by mindfulmike** [comment]
seems like using soundex was a bad idea. i'm going to go ahead and take it out.

**Comment by web-mech** [comment]
https://github.com/web-mech/badwords/releases/tag/v1.2.0
